### PR TITLE
[MQTT] never publish `force` to the `refresh/mode` to prevent never ending polling

### PR DESCRIPTION
**Pull request by tisoft**

### CODE REVIEW

**Review by mschmiedel — APPROVED** [review]
Looks fine to me, when I implemented it, I was not 100% sure if the state should be republished. 

However, since it is never sent to /set, it should not cause never ending polling, or does it? Still no need to publish the force state, this is also good if internally we need to call force, it does not cause such a propagation...

**Comment by tisoft** [comment]
If force is published to mqtt and then the gateway is restarted, it will load it'a configuration back from MQTT and the mode will be force and polling won't stop. This behavior was not caused by your change, but by my change that enabled the configuration loading from MQTT.

**Comment by tisoft** [comment]
(I know it can happen, because it happened to me.) 😇

**Comment by mschmiedel** [comment]
OK, I had not thought about that scenario, I was just wondering how this could happen, but after restart it makes sense...

**Pull request merged**
