### PR TITLE
[MQTT] initialize refresh configuration from MQTT topics

### PR DESCRIPTION
**Pull request by tisoft**
* Try to load the existing refresh configuration from MQTT
* If no configuration can be retrieved after 10s, start with default values

### CODE REVIEW

**Comment by tisoft** [comment]
@mschmiedel Since you did the base work of the refresh handling, could you take a look on this?

**Comment by mschmiedel** [comment]
Of course, but will be around the weekend...

**Comment by mschmiedel** [comment]
I just did a first check, I like the concept, I did not think of any "nice" way to listen to the topics at the begin without nasty threading stuff, this solution with the 10s grace period looks fine.

Only thing I believe that could happen (will try to test it on the weekend), is that after you set the first missing value, you will immediately get a value from the topic in the message handler, and since vehicle state is not complete yet, it will try to set it again, until all values are set. Have you made sure this is handled? 

Else I will finish reviewing it with a quick test in a few days...

**Comment by tisoft** [comment]
The setters check if the value has actually changed and only send an update to MQTT if it has, so we should not get any loops there.

**Comment by mschmiedel** [comment]
> The setters check if the value has actually changed and only send an update to MQTT if it has, so we should not get any loops there.

Yes, you are right, I saw that now...

**Comment by mschmiedel** [comment]
So, code looks fine for me.

I could test the following scenarios successfully:
- Read data from retained messages
- Partial init of absent data (just published a non-retained message before)
- Change settings and restart

So for me the MR looks fine...

**Review by mschmiedel — APPROVED** [review]
As mentioned before (should have added the comment here), looks fine for me.

**Review by mschmiedel — APPROVED** [review]

**Pull request merged**
