### PR TITLE
Add remaining charge time

### PR DESCRIPTION
**Pull request by mschmiedel**
First draft to see how it feels, will be testing it this week...

1. We should check what happens if charger is not connected. For me (about 70% battery) it is showing 1023 (minutes?). If charger not connected, maybe post "null"? 
2. Is minutes ok? Will be testing how tools like Home Assistant come along with this format.

### CODE REVIEW

**Comment by tisoft** [comment]
I also have 1023 as value if no charging is talking place. I would send 0 if charging is not taking place, since I don't like null values for integer mqtt fields, but I'm open for discussion.

Instead of sending minutes, we could send the value in ISO 8601: https://www.digi.com/resources/documentation/digidocs//90001488-13/reference/r_iso_8601_duration_format.htm

For example PT1H30M for 90 minutes.

**Comment by mschmiedel** [comment]
> I also have 1023 as value if no charging is taking place. I would send 0 if charging is not taking place, since I don't like null values for integer mqtt fields, but I'm open for discussion.
> 
> Instead of sending minutes, we could send the value in ISO 8601: https://www.digi.com/resources/documentation/digidocs//90001488-13/reference/r_iso_8601_duration_format.htm
> 
> For example PT1H30M for 90 minutes.

I agree with the 0, will check it further. 

About the ISO 8601, I will test it, tools like HomeAssistant might have issues parsing this kind of data; for example the last refresh state was quite a hassle to properly interpret, even though it is a standard datetime string with timezone...

**Comment by tisoft** [comment]
I have opened a discussion about time and duration formats, since I think we should keep them compatible between Java and python implementations.

https://github.com/orgs/SAIC-iSmart-API/discussions/6#discussioncomment-6208782

**Comment by mschmiedel** [comment]
> > I also have 1023 as value if no charging is taking place. I would send 0 if charging is not taking place, since I don't like null values for integer mqtt fields, but I'm open for discussion.
> > Instead of sending minutes, we could send the value in ISO 8601: https://www.digi.com/resources/documentation/digidocs//90001488-13/reference/r_iso_8601_duration_format.htm
> > For example PT1H30M for 90 minutes.
> 
> I agree with the 0, will check it further.
> 
> About the ISO 8601, I will test it, tools like HomeAssistant might have issues parsing this kind of data; for example the last refresh state was quite a hassle to properly interpret, even though it is a standard datetime string with timezone...

Did my first test with charger connected. Time is definitively in minutes. However, I am a bit unsure on how to handle it, one aspect is the standarization with other topics, the other one is how practicable it is at the end:

From the HomeAssistant perspective:
Adding the sensor as minutes works fine, but does no "smart" conversions
Adding the sensor with a template that adds the minutes to the current timestamp and represents the value as timestamp, will do quite fine:

`value_template: "{{ now() + timedelta(minutes = int(value)) }}"`

The other timestamps with the quotes are quite tricky, the quote is only a small part or the problem, it will only work with something like this:

`value_template: "{{ ((value[:-9] | replace('\"', '') | replace('T', ' ') | as_timestamp) + 3600 * now().timetuple().tm_isdst) | timestamp_local }}"`

If we choose to standarize, I would think of doint everything in some kind of timestamp als long value, this allows the user to freely choose how to use it, however it is not easy to read if checking the topic... Maybe offer both options at some time?

**Comment by mschmiedel** [comment]
As a little comment: this is the reason why I struggle with the ISO duration:

https://community.home-assistant.io/t/how-to-convert-iso-duration-to-seconds/56329/5

I would agree with some schema that offers stuff like 

```
.../drivetrain/remainingChargeTime/iso8601
.../drivetrain/remainingChargeTime/timestamp
```

Or maybe send a json object with both representations. This could apply to all date fields, being the topic hierarchy at least backwards compatible with current implementations. 

ISO:
Advantage: human readable
Disadvantage: can be a hassle to interpret in certain tools

Timestamp:
Advantage: any tool should be able to handle it
Disadvantage: bad if you want to manually look at the date in the topics and understand what is going on.

**Comment by tisoft** [comment]
Since we have `charging`, `chargingType`, `running` topic names, maybe we should call this `remainingChargingTime`?

**Comment by mschmiedel** [comment]
> Since we have `charging`, `chargingType`, `running` topic names, maybe we should call this `remainingChargingTime`?

Done! :)

**Pull request merged**
